### ISSUE TITLE
Computational Graph: Switch to OpenAPI

### ISSUE THREAD

**Issue by raprasad** [privacytoolsproject/yarrow#24]
## Switch to OpenAPI

  1. Rewrite definitions
  2. Adjust python and R bindings
  3. serialization/deserialization
     1. rust: serde, openapi
      1. python: update ctypes

**Comment by Shoeboxam** [comment]
One of the big reasons why I considered OpenAPI a viable replacement for protobuf was that I had the option to generate only the model files. Unfortunately, this option is more of a filter, and in various languages the generated files still contain broken references/imports to server configuration/setup within the generated code. I have workable model generation/serialization/deserialization in rust (in the openapi branch), but using models alone won't work in Python or R (or Go, csharp, java, etc). Also, rust openapi generation is spotty (the most relevant tool still breaks on OneOf?)

I am moving forward with protobuf. I'm still open to adding translations from OpenAPI to the proto generated traits in the validator if a more viable code generation tool for data models in OpenAPI is demonstrated, or an alternative implementation idea is proposed.
