### ISSUE TITLE
Run graph from in-memory data?

### ISSUE THREAD

**Issue by joshua-oss** [privacytoolsproject/yarrow#38]
What's the best approach to execute the analysis against in-memory data?  We'll need in-memory to pass in the SQL intermediate results from burdock, and bypassing file access will speed up the stochastic tester independent of the SQL pieces.

**Comment by Shoeboxam** [comment]
The UI for this has improved. Here is an example:
https://github.com/privacytoolsproject/yarrow/blob/5fae23a5d1269b072dbb814a902ea53db93ede28/bindings-python/tests/test_base.py#L68-L80

I did introduce a regression yesterday, which breaks the mean. The regression will be fixed once I complete the core validator code.
